### ISSUE TITLE
Issue under Matlab2018b

### ISSUE THREAD

**Issue by musall** [sg-s/umap-matlab-wrapper#11]
Calling u=umap() in my Matlab2018b installation produces this error: 
"The specified superclass 'Constructable' contains a parse error, cannot be found on MATLAB's search path, or is shadowed by another file with the same name."

Could this be a Matlab version issue?

Thanks!
Simon

**Comment by sg-s** [comment]
NO, it's my bad. there's a missing dependency. ~~let me fix that~~

You need another library called [mtools](https://github.com/sg-s/srinivas.gs_mtools/)

Download that and add that to the path and you should be good. Let me know if that fixes your issue @musall

**Comment by sg-s** [comment]
Should be fixed now... @musall can you check now?

**Comment by musall** [comment]
This fixed the issue. Thank you for the quick response!
 
The fitting still doesn't work because I can't switch to the umap environment with condalab (see below). Do you have a suggestion on how I could correct that? Thanks again!

>> conda env list
base     C:\Anaconda3
locaNMF     C:\Anaconda3\envs\locaNMF
locanmf     C:\Anaconda3\envs\locanmf
*umap     C:\Anaconda3\envs\umap
wfield     C:\Anaconda3\envs\wfield

>> conda activate umap

>> conda.test
The python executable I am using is located at: 
C:\Anaconda3\python.exe

**Comment by musall** [comment]
I've found the issue for condalab: In my umap environment, there is no subfolder 'bin' and 'python.exe' is under 'C:\Anaconda3\envs\umap'. Deleting the step that adds 'bin' in the 'setenv' function fixed it.

Now I get an error 'Importing the numpy C-extensions failed.' although the correct NumPy version is detected. So, progress :)

**Comment by sg-s** [comment]
Hmmm, so you're on windows and trying to use condalab? I see. 

First, let's make sure your python install works.

Can you in your shell (outside matlab)

```
conda activate umap
```

and then launch a python REPL and try

```
import umap
```

Does that work?

**Comment by musall** [comment]
Yes, importing and using umap in its environment works fine in python. 
When comparing the paths in Python and Matlab, I found some folders that were missing in Matlab: 

('C:\\Anaconda3\\envs\\umap\\Library\\mingw-w64\\bin', 'C:\\Anaconda3\\envs\\umap\\Library\\usr\\bin', 'C:\\Anaconda3\\envs\\umap\\Library\\bin', 'C:\\Anaconda3\\envs\\umap\\Scripts', 'C:\\Anaconda3\\envs\\umap\\bin')

After adding them in, the NumPy error went away but I still can't import h5py. I'm suspecting there is something else missing in the path under Matlab.

Sorry for bothering you, I didn't realize condalab wasn't built for Windows. 
If this turns out be a bigger issue I'll just stick to using umap in Python.

**Comment by musall** [comment]
After your suggestion, I managed to get it to work by adding  'conda activate umap' directly to the system call for run_umap.py,  when using the fit function (R = u.fit(X)).
eval_str =  ['conda activate umap & ', p1 filesep 'run_umap.py" ' self.metric];

It seems like changing the path with condalab didn't achieve the same outcome but I'm perfectly fine with this workaround. 

Thank you for the help and let me know if you'd like more feedback :)

**Comment by sg-s** [comment]
I'm glad this works for you...yes, I don't have access to a windows computer so it's hard for me to fix this because I don't know what's wrong. It's clearly a path issue. If you do manage to figure this out please send me a PR at https://github.com/sg-s/condalab

Closing this for now!
